export * from "./core/wrapDirecte";
export * from "./types";
export * from "./types/auth";
export * from "./types/grades";
export * from "./types/timetable";
export * from "./types/homework";
export * from "./types/messaging";
export * from "./types/documents";
export * from "./types/schoollife";
